### ISSUE TITLE
Write a spec file to generate the binaries with pyinstaller

### ISSUE THREAD

**Issue by Ati1707** [Ati1707/DazContentInstaller#23]
Using a optimized spec file has a lot of benefits.
Lower binary size by excluding not needed parts of third party libraries and if I understood the documentation correctly if we decide to create a second binary for the updater we can share modules between those two binaries.

**Comment by malikrohail** [comment]
can i fix

**Comment by Ati1707** [comment]
> can i fix

Hi, yes, of course! However, the requirements for this issue have changed slightly. I mentioned this in the initial issue, but now we need the features to support two Python scripts because I want to release the updater either today or tomorrow.

I’ve created a .spec file to compile both Python scripts (main and updater). After skimming the PyInstaller documentation and browsing some GitHub and Reddit discussions, I identified a few optimizations we can prioritize:

    Allow both binaries to share modules.
    Exclude optional modules.
    Optimize bytecode (likely only worth applying to the main application).

I just pushed the branch to GitHub so you can take a look at the .spec file. For now, I’ve mostly copy-pasted the command used for the main app. The updater script isn’t working yet—I was out yesterday and still need to work on it.

Here’s the link to spec file I created:
https://github.com/Ati1707/DazContentInstaller/blob/always-update-a-running-system/DazContentInstaller.spec

**Comment by Ati1707** [comment]
Closing this as creating the spec file is not necessary anymore. I decided to stay away from writing an updater. The frequency of code changes will go down by a lot when the first version releases no reason to invest time into making an updater
